import { defineConfig } from "oxfmt";

export default defineConfig({
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  ignorePatterns: [],
  insertFinalNewline: true,
  jsdoc: false,
  jsxSingleQuote: false,
  objectWrap: "preserve",
  overrides: [],
  printWidth: 100,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  semi: true,
  singleAttributePerLine: false,
  singleQuote: false,
  sortImports: true,
  sortPackageJson: true,
  sortTailwindcss: true,
  svelte: { allowShorthand: true, indentScriptAndStyle: true },
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
  vueIndentScriptAndStyle: false,
});
