name: Build/Release Grabbr

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download Binaries
        run: bun run down

      - name: Verify binaries (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          resources/bin/ffmpeg -version
          resources/bin/ffprobe -version
          resources/bin/yt-dlp --version

      - name: Verify binaries (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          resources\bin\ffmpeg.exe -version
          resources\bin\ffprobe.exe -version
          resources\bin\yt-dlp.exe --version

      - name: Install Dependencies
        run: bun install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          # sudo snap install snapcraft --classic
          bun run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: bun run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: bun run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
