name: Build/Release Grabbr

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-26, macos-26-intel, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build:desktop:stable
        env:
          TURBO_TELEMETRY_DISABLED: 1

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: apps/desktop/artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
